### ISSUE TITLE
Unecessary dependencies

### ISSUE THREAD

**Issue by lbruun** [f4b6a3/uuid-creator#1]
The library is hard to use because it brings with it too many transitive dependencies. These dependencies may conflict with other parts of your application.

This is a shame, because in itself the library has no dependencies. It is all due to the _benchmarking_ which is part of the library, but shouldn't be.  The solution is to put the benchmarking in a separate Maven module.

**Temporary workaround**

Until this is fixed, people can use the `uuid-creator` library in the following way in their applications:

```
<dependency>
	<groupId>com.github.f4b6a3</groupId>
	<artifactId>uuid-creator</artifactId>
	<version>0.9.0</version>
	<exclusions>
		<exclusion> 
			<groupId>org.openjdk.jmh</groupId>
			<artifactId>jmh-core</artifactId>
		</exclusion>
		<exclusion> 
			<groupId>org.openjdk.jmh</groupId>
			<artifactId>jmh-generator-annprocess</artifactId>
		</exclusion>
		<exclusion> 
			<groupId>com.fasterxml.uuid</groupId>
			<artifactId>java-uuid-generator</artifactId>
		</exclusion>
		<exclusion> 
			<groupId>com.eaio.uuid</groupId>
			<artifactId>uuid</artifactId>
		</exclusion>
	</exclusions>   
</dependency>

```

**Comment by fabiolimace** [comment]
Removed unecessary dependencies.
