### ISSUE TITLE
uuid-ncname-58

### ISSUE THREAD

**Issue by blop** [f4b6a3/uuid-creator#104]
Hello,

According to https://datatracker.ietf.org/doc/html/draft-taylor-uuid-ncname#name-encoding-algorithm, there is a uuid-ncname-58 that is forseen. Will it be supported by this library also ?

Thank you!
Regards,

Olivier

**Comment by fabiolimace** [comment]
Hello @blop !

For now, I'm not planning to add support for ncname-58.

However, if you only need a base-58 encoding, you can use [`Base58BtdCodec`](https://github.com/f4b6a3/uuid-creator/blob/39575d55d0304aed388812885615ffbdfb7f27dc/src/main/java/com/github/f4b6a3/uuid/codec/base/Base58BtcCodec.java#L38):

```java
Base58BtcCodec codec = new Base58BtcCodec();
System.out.println(codec.encode(UUID.randomUUID()));
System.out.println(codec.encode(UUID.randomUUID()));
System.out.println(codec.encode(UUID.randomUUID()));
```
```
RErkpFw5zFXPMbA8LuJRBJ
2Lpf9CqQt7fKfz9P3hrjnS
EWP984vucSkhfUGJPNSutN
```
