### ISSUE TITLE
please release 2.0.0 as soon as possible

### ISSUE THREAD

**Issue by rohithXluffy** [f4b6a3/uuid-creator#11]

**Comment by fabiolimace** [comment]
Done.

**Comment by rohithXluffy** [comment]
Thanks Fabio Lima.
Missing artifact com.github.f4b6a3:uuid-creator:jar:2.0.0 when imported in maven.can you please check this.

**Comment by fabiolimace** [comment]
I think it can take a few hours to be available on maven central.
Pleas, try again later.

**Comment by rohithXluffy** [comment]
Thanks Fabio Lima.
