### ISSUE TITLE
Java 8 Compatibility

### ISSUE THREAD

**Issue by ahmadimt** [f4b6a3/uuid-creator#12]
I want to use this library in one of my projects. We are still using Java 8 and the latest version of this library is compatible with JDK 11 and above. Can we please make this JDK 8 compatible. I guess, Java 8 is still widely used.

I can submit a PR for this.

**Comment by fabiolimace** [comment]
The PR will be accepted based in these articles:

* [The State of Developer Ecosystem 2019 for Java - JetBrains](https://www.jetbrains.com/lp/devecosystem-2019/java/)
* [The State of Java: Trends And Data For One of the World’s Most Popular Programming Languages](https://blog.newrelic.com/technology/state-of-java/)
* [The State of Java in 2020: Java 8 is still ahead](https://jaxenter.com/the-state-of-java-2020-169875.html)
* [Top Java technologies in 2020 – JVM programming languages, IDEs, tools & more](https://jaxenter.com/top-java-technologies-2020-167900.html)

**Comment by fabiolimace** [comment]
PR merged.

**Comment by fabiolimace** [comment]
Version 2.1.0 available in a few hours.
