### ISSUE TITLE
add UuidCreator namespace somewhere

### ISSUE THREAD

**Issue by xenoterracide** [f4b6a3/uuid-creator#15]
for some reason intellij didn't want to auto import, so I had to go digging in the source. Would be good to add it to the doc.

**Comment by fabiolimace** [comment]
@xenoterracide Caleb Cushing,

I added public constants into `UuidCreator` to hold the predefined name spaces and local domains. I hope it can fix the problem for Intellij developers.

I also 'unlocked' more methods into `UuidCreator` to generate name-based and DCE security UUIDs. Maybe it will be useful for developers that need more than the predefined name spaces and local domains. Now they can use their own custom values, with no need to import the internal UUID creators (`NameBasedMd5UuidCreator`, `NameBasedSha1UuidCreator` and `DceSecuriteUuidCreator`).

Add public constants to 'UuidCreator':
- NAMESPACE_DNS
- NAMESPACE_URL
- NAMESPACE_ISO_OID
- NAMESPACE_X500_DN
- LOCAL_DOMAIN_PERSON
- LOCAL_DOMAIN_GROUP
- LOCAL_DOMAIN_ORG
    
Add methods to 'UuidCreator':
- getNameBasedMd5(UUID namespace, String name)
- getNameBasedMd5(UUID namespace, byte[] name)
- getNameBasedSha1(UUID namespace, String name)
- getNameBasedSha1(UUID namespace, byte[] name)
- getDceSecurity(byte localDomain, int localId)
- getDceSecurityWithMac(byte localDomain, int localId)

Thank you!

**Comment by fabiolimace** [comment]
Version 2.3.0 will be available on maven central today.
