### ISSUE TITLE
Creators in UiidCreator are not thread-safe

### ISSUE THREAD

**Issue by lbruun** [f4b6a3/uuid-creator#2]
The static creators in `UiidCreator` are lazily initialized but not in a thread-safe manner. (concurrent invocations may lead to incorrect/duplicated initialization of the singleton)

See https://en.wikipedia.org/wiki/Initialization-on-demand_holder_idiom for solution.

Here is the current code:

```java
public class UuidCreator {

    private static RandomUuidCreator randomCreator;

    public static UUID getRandom() {
        if (randomCreator == null) {
            randomCreator = getRandomCreator();
        }
        return randomCreator.create();
    }
}
```

and here is the equivalent with the thread-safe idiom applied:

```java
public class UuidCreator {

    public static UUID getRandom() {
        return RandomCreatorLazyHolder.INSTANCE.create();
    }

    private static class RandomCreatorLazyHolder {
        static final RandomUuidCreator INSTANCE = getRandomCreator();
    }
}
```

Btw: Really like where you are taking this library.  It is on the path to become *the* UUID library for Java.

**Comment by fabiolimace** [comment]
I didn't know that idiom for concurrent calls.
Thank you!
