### ISSUE TITLE
MAC address: NetworkInterface.getNetworkInterfaces() is expensive

### ISSUE THREAD

**Issue by lbruun** [f4b6a3/uuid-creator#3]
In relation to:

```java
protected long getHardwareAddress() {
    try {
        byte[] mac;
        NetworkInterface nic;
        List<InterfaceAddress> list;
        Enumeration<NetworkInterface> enm;

        enm = NetworkInterface.getNetworkInterfaces(); // VERY EXPENSIVE !!
        while (enm.hasMoreElements()) {
            nic = enm.nextElement();
            list = nic.getInterfaceAddresses();
            mac = nic.getHardwareAddress();
            if ((mac != null) && (!list.isEmpty()) && !(nic.isLoopback() || nic.isVirtual())) {
                return ByteUtil.toNumber(mac);
            }
        }
    } catch (SocketException | NullPointerException e) {
        // (2) return random number
        return getRandomMulticastNodeIdentifier();
    }
    // (2) return random number
    return getRandomMulticastNodeIdentifier();
}
```

Just a hint about my experience with [NetworkInterface.getNetworkInterfaces()](https://docs.oracle.com/javase/8/docs/api/java/net/NetworkInterface.html#getNetworkInterfaces--). This is a potential long-running operation. On my Windows box it takes 1200 msecs and returns some 45 entries. The reason is that Windows seems to create a lot virtual/bogus network interfaces which you cannot see with `ipconfig /all` command. From my tests it is the creation of the enumeration which takes time. Traversing the enumeration seems to have no overhead. 

It is not a problem per-se in the library's current implementation because it is called only once, but the expensiveness of this call may be noted in the code and relevant places in Javadoc. For UI type applications a delay of 1,2 secs causes a noticeable delay.

**Comment by fabiolimace** [comment]
I've created the class `SystemUtil` to get network information. Now I try to find the MAC in two steps. First the method getLocalHost() is used to find the network interface associated to the host name. If it fails, it iterates over all network interfaces. I hope that using `getLocalHost()` the problem is solved for most cases on Windows boxes.
