### ISSUE TITLE
UUID Slugs

### ISSUE THREAD

**Issue by buko** [f4b6a3/uuid-creator#30]
First off, great lib. The functionality provided and the quality of the code are impressive.

I wonder if you'd be interested in supporting UUID Slugs?

UUID Slugs are a base64 encoding of UUIDs that can be safely included in URLs and even file names. This sort of functionality is very commonly required and I think instead of continuing to replicate it in project after project it should be implemented once in a project like uuid-creator.

A UUID Slug is the string generated by (url safe) Base64 encoding a UUID and then stripping the padding resulting in a 22-character string that can be safely used in filenames and URLs. This functionality isn't directly related to creation but could be stored in a sub-package like f4b6a3.uuid.slug.

See also:

* [Creating Base64 UUID in Java](https://sakthipriyan.com/2017/04/02/creating-base64-uuid-in-java.html)
* [slugid - Compressed UUIDs for Node.js](https://github.com/taskcluster/slugid) 
* [Slugid - Compressed UUIDv4](https://pub.dev/packages/slugid)
* [URL safe UUIDs in the smallest number of characters](https://stackoverflow.com/questions/11431886/url-safe-uuids-in-the-smallest-number-of-characters)

**Comment by buko** [comment]
See #32 . Rather than having lots of static methods you could introduce a single generic interface and provide lots of different implementations of the UuidCodec class. This would work well especially with client code that uses dependency injection.

**Comment by fabiolimace** [comment]
Yesterday I implemented the UUID Slug codec. I also created many base-n codecs that can be used by the slug codec. The default base-n codec is base-64-url.

I also included an option to shift the variant and version bits to the beginning of the byte array. It is similar to the "NICE" slug in the libs you listed, but its much simpler. This option shifts the 2 bits of the variant to the positions 0 and 1. And then shifts the 4 bits of the version to the positions 2 to 5. The result of the shifts is that the first character of the slug is a letter (when using base-32 and base-64 codecs).

Please see the following examples.

This example prints 10 slugs encoded to **base-32**:

```java
public static void slugCodec32() {

	UuidBase32Codec baseCodec = new UuidBase32Codec();
	UuidSlugCodec slugCodec = new UuidSlugCodec(baseCodec);

	for (int i = 0; i < 10; i++) {
		String slug = slugCodec.encode(UUID.randomUUID());
		System.out.println(slug);
	}
}
```

```
QDUAW5IAPRGJ3HISWUUV4JXN4Q
KNO5R3775VFXLFXYDFEB5PNDIY
S255C6Q7NZH5RKMJFVHYRJQXNA
KA3V4HBPRNFAXGDEPX5P36RAQM
AXCYFEQP4BE5LPY3ICF6JEJLSM
RESL3HQCFRGWLN6DHIMPNUP5GQ
SC2G4J3NVZC7LIZOIDMTAK7B3M
M5VW5JDPRFFZJDIEMCLIEFHA4M
PCGTLZPKVJAJVF55UOQOAYSJIQ
EZXOVCS6NJEQDMF2LC25QVYIPA
```

This example prints 10 slugs encoded to **base-64-url** (default base-n codec):

```java
public static void slugCodec64() {

	UuidSlugCodec slugCodec = new UuidSlugCodec(); // default base-64

	for (int i = 0; i < 10; i++) {
		String slug = slugCodec.encode(UUID.randomUUID());
		System.out.println(slug);
	}
}
```

```
tOvsNifHQceCq-TFfVzjww
QhgK9io0TneRtxOwMyINSg
OjRLb6YiRni6r8A6kNQqag
AxP5AyWUR-qxY23Yul3MDA
5dkLES-WTlC4wqn5LgnhkQ
RCsTieaWTwy47xUFp_hJQQ
KO345zetRN6C9vusZueh4g
rnwLa3j4RzG-0Cy1arQaYQ
-xEVLUWfRIa45QyT5gO_dA
-o-SGwZbT8G0g2ZpqvgxOg
```

This example prints 10 slugs encoded to **base-32** with bit shift of variant and version bits to the beginning of the byte array:

```java
public static void slugCodec32_WithBitShift() {

	boolean shift = true;
	UuidBase32Codec baseCodec = new UuidBase32Codec();
	UuidSlugCodec slugCodec = new UuidSlugCodec(baseCodec, shift);

	for (int i = 0; i < 10; i++) {
		String slug = slugCodec.encode(UUID.randomUUID());
		System.out.println(slug);
	}
}
```

```
SM6SYS4XMAPM74ZZVHRDLPZDUY
SJVKD4UIM76B2DHJINSVYMHMRI
SE36NQB4QZRFZL3GNTI6LGHEUU
SG6LJCQ6YRZHLUWQGKTSPPDYDQ
SACOWIAD6EKXT5ZAPLZF3IRL3Y
SBHZL3MJYQH2YUYF324BXQ5HFU
SLAAOD6AE5ZIUG5YWFGMUD2SWA
SEPAA5ZYPF2L2NBMZIFHUAR7PE
SNBJUKZP4DN3TQZXWL3IZFRRRA
SDVXRJ6KJBP3Z6P3MWVZ2EVT7Y
^ prefix 'S'
```

This example prints 10 slugs encoded to **base-64-url** (default base-n codec) with bit shift of variant and version bits to the beginning of the byte array:

```java
public static void slugCodec64_WithBitShift() {

	boolean shift = true;
	UuidSlugCodec slugCodec = new UuidSlugCodec(shift); // default base-64

	for (int i = 0; i < 10; i++) {
		String slug = slugCodec.encode(UUID.randomUUID());
		System.out.println(slug);
	}
}
```

```
kyM9XV0cpTX2fm6YD1zOzw
kXqGPB-iiqcZy5CwpMB3QQ
k_rJlYzcP334sg1quSjl8g
k_kOOw1iPGGQEUKSbMf_OA
kYfp91PMEwuz1Led3_3FZA
kySJUE4BF2gsFThh_lylyA
keDP7ecpz37zvwab1_M2YA
k6FPwVqozUhCC7FZepD2Jg
k5CCMlHHJ5IW_FmZxQDjjA
kwcO0hLYWzpT69fbGQLB0g
^ prefix 'k'
```

**Comment by fabiolimace** [comment]
Added support to case insensitive base-n codecs.

Changed the base-16 and base-32 codecs to:
1. Encode to lower case // YELLING IS RUDE!
2. Decode from lower and upper cases

**Comment by fabiolimace** [comment]
@buko , I forgot to ask what you think about the codecs. Let me know if you find any problems with them or make a pull request if you wish.

If you approve them, a new version in the next weekend.

**Comment by buko** [comment]
This stuff looks great, even better than I hoped. The only thing missing is Javadoc; you might just want to add a link to the github issues that explains what the codecs do. 

Another question is threadsafety. It looks like all the code works with immutable lookup tables and should be threadsafe but you might want to make that explicit. Java should have a standard @ThreadSafe annotation to make this clear but it doesn't.

Personal preference: most of the codecs, like UuidSlugCodec, UuidNameCodec, and the well-defined base encodings should be final. Not a big deal either way but I wouldn't expect these classes to ever be subclassed.

The name of https://github.com/f4b6a3/uuid-creator/blob/773c8b1e8a3b23e423e7b05e44a3fd1523ef3ee6/src/main/java/com/github/f4b6a3/uuid/codec/UuidStringCodec.java is a bit confusing. Maybe use a clearer name like 'CanonicalStringCodec' and include a link to [Wikipedia](https://en.wikipedia.org/wiki/Universally_unique_identifier#Format) that explains what the canonical string format of a UUID is.

It's really nice to see all this functionality collected in one place under the MIT License. Great job!

**Comment by fabiolimace** [comment]
@buko

Version 3.4.0 has been released.

Thank you very much for your help!
