### ISSUE TITLE
UUID Names

### ISSUE THREAD

**Issue by buko** [f4b6a3/uuid-creator#31]
Would be nice to support UUID NCName Encoding.

UUID NCName Encoding provides a mechanism to convert UUIDs to/from strings that are valid NCNames which can be used in XML documents and other contexts. ([NCNames are strings not allowed to contain hyphen ('-) characters and not start with a digit.](https://www.w3.org/TR/REC-xml-names/#NT-NCName))

One interesting scheme is outlined in [this RFC](https://tools.ietf.org/html/draft-taylor-uuid-ncname-00) and implemented in [p5-data-uuid-ncname](https://github.com/doriantaylor/p5-data-uuid-ncname).

This functionality isn't directly related to UUID creation but could be implemented in a subpackage like f4b6a3.uuid.name. This sort of functionality gets re-implemented a lot so I always figure it'd be useful to place it in a single "best of breed" library.

**Comment by fabiolimace** [comment]
Sorry again for the silence.

I had some doubts about the necessity of this new feature. But I think it could be useful to create unique identifiers that doesn't start with a digit.

In the new version this utility class will be present:

```java
public final class UuidNcname {

	public static String toNcname32(UUID uuid);
	public static UUID fromNcname32(String ncname);
	
	public static String toNcname64(UUID uuid);
	public static UUID fromNcname64(String ncname);
}
```

This class implements the NCName outlined in the RFC draft. It is also kind of a support to the initiative of the developer who proposed the draft.

Thank you for all your suggestions!

**Comment by buko** [comment]
> But I think it could be useful to create unique identifiers that doesn't start with a digit.

Yeah, it actually is surprisingly useful. Lots of systems, not just XML documents, don't like identifiers that start with a digit (including Java itself and some older transactional file systems). I run into this problem all the time.

I'm not totally sure on the need for toNcname32/fromNcname32 -- case insensitive identifiers are an anti-pattern but there's certainly some system out there that treats identifiers in a case insensitive manner.

**Comment by fabiolimace** [comment]
Yesterday the NCName codec was implemented. The default base-n codec is base-64-url.

This example lists 10 NCName strings created by the NCName codec.

```java
UuidCodec<String> ncnameCodec = new UuidNcnameCodec();

for (int i = 0; i < 10; i++) {
	UUID uuid = UUID.randomUUID();
	String ncname =  ncnameCodec.encode(uuid);
	System.out.println(ncname);
}
```

```
EKDFIkE5KZs5945P4juWvI
EZxA3BE8eTTygBz3dC0iPI
EAfihqR-9-hC3Cj-eJ6VEK
EJCSbgQQBwXeeUsJH3m2jK
E_-lyYqIN_V1iY0eUZonxJ
ERus2Ykrl-wiF9TUSAeNGJ
E5ml0Gcl7aMuG7QtITHlNI
EfrFga58dw8nP7D-qUNYwL
E-90kIDnTe3l3JjeheZvUI
ExdBXVL6MUWwTEkSd7-5EK
```

**Comment by fabiolimace** [comment]
@buko

Version 3.4.0 has been released.

Thanks for your help!

**Comment by buko** [comment]
Hey Fabio, 

Thanks for all the great work! We will pick this up tomorrow on Monday and start using it!
