### ISSUE TITLE
UUID URIs

### ISSUE THREAD

**Issue by buko** [f4b6a3/uuid-creator#32]
UUIDs can be represented as URIs (specifically URNs) using the standardized scheme in [RFC 4122](https://tools.ietf.org/html/rfc4122). This basically involes pre-pending 'urn:uuid:' to the UUID text representation eg 'urn:uuid:f81d4fae-7dec-11d0-a765-00a0c91e6bf6'.

It would be useful to provide code for converting such URIs to UUIDs and converting UUIDs to such URIs. This code isn't directly related to UUID generation but could be stored in a sub-package like f4b6a3.uuid.uri. Again, sorry to spam your project, but I'd love to see all this UUID-related functionality implemented once in a single best of breed library instead of replicated in project after project.

**Comment by fabiolimace** [comment]
Sorry for the delay. I'm already working on It.

I think the URNs scheme is closely related to UUIDs, since the RFC-4122 purpose is to define a URN for UUIDs. So it's necessary to add some methods to convert to and from URNs, after checking wether the input is valid.

This utility class will be available in the next version:

```java
class UuidUrn {
    public UUID toUuid(String urn);
    public String fromUuid(UUID uuid);

    public String toUuidString(String urn);
    public String fromUuidString(String uuid);
}
```

For example, if you need to get a URN **from a UUID String**, you will do this:

```java
String urn = UuidUrn.fromUuidString("f0c2ca84-fb13-4b2e-8c6d-1d3339892188");
// urn = "urn:uuid:f0c2ca84-fb13-4b2e-8c6d-1d3339892188"
```
If you need to turn a URN **into a UUID String**:

```java
String uuid = UuidUrn.toUuidString("urn:uuid:33bcc7ef-6598-4fe8-bdb2-5885a96c0431");
// uuid = "33bcc7ef-6598-4fe8-bdb2-5885a96c0431";
```
The other two methods work the same way, but convert UUID objects to and from Strings.

**Comment by buko** [comment]
Such an API works but you might consider but I wonder if you might consider using a generic API? All of the desired functionality is about encoding/decoding UUIDs and could be subsumed under a single generic interface. I think something like this would work:

```
public interface UuidCodec<E> {
  public E encode(UUID uuid) throws CodecRuntimeException;
  public UUID decode(E item) throws CodecRuntimeException;
}
```

Then the UUID URN scheme can be described by `UuidUrnCodec extends UuidCodec<java.net.URI>`.

UUID Slugs and the other String schemes can be described by `UuidSlugCodec extends UuidCodec<String>`.

A person who wants to do the conversion could then do something like:

```
final UuidCodec<URI> urnCodec = new UuidUrnCodec();
String urn = urnCodec.encode(UUID.fromString("f0c2ca84-fb13-4b2e-8c6d-1d3339892188"));
UUID urn = urnCodec.decode(URI.create("urn:uuid:33bcc7ef-6598-4fe8-bdb2-5885a96c0431"));
```

Subsuming all this functionality under a single generic UuidCodec interface feels cleaner and more flexible than having lots of static methods running around. It also has the added benefit of decoupling client code a bit. A lot of the code that would use such functionality doesn't really need to care about the implementation of the UUID codec, it just needs an object that does it. If another scheme comes along then the code doesn't have to change at all.

**Comment by fabiolimace** [comment]
Great! I'll do this. Maybe in a few days I'll make some commits.

**Comment by fabiolimace** [comment]
Yesterday the URI codec was implemented.

This example lists 10 `java.net.URI` objects created by the URI codec.

```java
UuidCodec<URI> uriCodec = new UuidUriCodec();
		
for (int i = 0; i < 10; i++) {
	UUID uuid = UUID.randomUUID();
	URI uri =  uriCodec.encode(uuid);
	System.out.println(uri);
}
```

```
urn:uuid:014c78ac-5f46-426f-b28f-5c35be6aed79
urn:uuid:a2a2cea8-a557-4464-abab-d5a48920fb10
urn:uuid:bca7ece7-57cb-4545-8e7b-72be56784d1f
urn:uuid:81e08774-038d-4754-89d0-39d7f88d254f
urn:uuid:ae95757e-fb07-4139-8b28-92e5261af531
urn:uuid:89f13b22-3c26-47c3-9be7-e33c777bf227
urn:uuid:6c0e4fd9-3645-4fbe-a763-4b6838f914a6
urn:uuid:12b897d5-fd69-40af-afbd-f35c24b38f91
urn:uuid:1acdcb5e-b9dd-4eb3-9720-590fff3d8c58
urn:uuid:a96ad018-7be8-4288-a26e-47a7890b4770
```

**Comment by fabiolimace** [comment]
@buko

Version 3.4.0 has been released.

Thanks for your help!
