### ISSUE TITLE
performance table with comb, ulid, tsid

### ISSUE THREAD

**Issue by nimo23** [f4b6a3/uuid-creator#33]
Hi,

to compare all available generators, it would be nice to include comb.

I did a little benchmark with timebased uuid and ulid (where each of it generates 100 id's):
- Ulid took approx. **15 millis** for generating 100 ID's 
- Time Based UUID took approx. **1 millis** for generating 100 ID's

Thanks and greetings!:

**Comment by fabiolimace** [comment]
There's a table that compares all generators in [uuid-creator-benchmark](https://github.com/fabiolimace/uuid-creator-benchmark).

**Comment by nimo23** [comment]
Thanks, the benchmark makes clear that:

- `UlidCreator02_UlidString`    is faster than `UuidCreator08_TimeBased`.
- `UuidCreator08_TimeBased` is faster than `UuidCreator04_PrefixComb`.
