### ISSUE TITLE
extractInstant() from Comb-String

### ISSUE THREAD

**Issue by nimo23** [f4b6a3/uuid-creator#35]
One question:

How can I get the Instant from a comb which comes from a String?

`var combString = UuidCreator.getPrefixComb().toString();`

There is a `UuidUtil.extractInstant()`, `UlidUtil.extractInstant()`, but no `CombUtil.extractInstant()`.

**Comment by fabiolimace** [comment]
When COMB generators were implemented, the extraction methods were left to be implemented in the future. I wasn't sure if anyone was going to need it.

I just released version 3.5.0. The following methods are now available:

- CombUtil.extractPrefix(): returns the unix millis from Prefix COMBs;
- CombUtil.extractSuffix(): returns the unix millis from Suffix COMBs;
- CombUtil.extractPrefixInstant(); // returns the instant from Prefix COMBs;
- CombUtil.extractSuffixInstant(); // returns the instant from Suffix COMBs.

No extraction method was implemented for Short Prefix COMBs and Short Suffix COMBs.
