### ISSUE TITLE
IETF Draft Update 4

### ISSUE THREAD

**Issue by d-schmidt** [f4b6a3/uuid-creator#67]
Version 6 (timeordered) has been changed to:

**UUID version 6 (UUIDv6)**
    A re-ordering of UUID version 1 so it is sortable as an opaque sequence of bytes. Easy to implement given an existing UUIDv1 implementation. See [Section 5.1](https://www.ietf.org/id/draft-peabody-dispatch-new-uuid-format-03.html#uuidv6)
**UUID version 7 (UUIDv7)**
    An entirely new time-based UUID bit layout sourced from the widely implemented and well known Unix Epoch timestamp source. See [Section 5.2](https://www.ietf.org/id/draft-peabody-dispatch-new-uuid-format-03.html#v7)
**UUID version 8 (UUIDv8)**
    A free-form UUID format which has no explicit requirements except maintaining backward compatibility. See [Section 5.3](https://www.ietf.org/id/draft-peabody-dispatch-new-uuid-format-03.html#v8)
**Max UUID**
    A specialized UUID which is the inverse of [[RFC4122](https://www.ietf.org/id/draft-peabody-dispatch-new-uuid-format-03.html#RFC4122)], [Section 4.1.7](https://rfc-editor.org/rfc/rfc4122#section-4.1.7) See [Section 5.4](https://www.ietf.org/id/draft-peabody-dispatch-new-uuid-format-03.html#maxuuid)

**Comment by fabiolimace** [comment]
UUID v6 had already been implemented several versions ago (`TimeOrderedFactory`).

Implemented for version v5.0.0:
* UUID v7 (`TimeOrderedEpochFactory`);
* UUID v8 (minimum support);
* Max UUID.

**Comment by fabiolimace** [comment]
Released v5.0.0.

Thank you for your request!
