### ISSUE TITLE
add fast ulid creator in benchmark

### ISSUE THREAD

**Issue by nimo23** [f4b6a3/uuid-creator#7]
The ulid-creator has 

`UlidCreator.getFastUlid()`

coming from

`UuidCreator.getUlidBasedCreator().withFastRandomGenerator().create().toString()`.

Could you add the fast ulid creator in this benchmark?

```
Throughput.UuidCreator_FastUlidBasedGuid
AverageTime.UuidCreator_FastUlidBasedGuid
```

**Comment by fabiolimace** [comment]
The thoughput difference is very small between the methods `UlidCreator.getUlid()` and UlidCreator.getFastUlid(). I think these methods spend more time incrementing the internal counter than calling the method `Random.getLong()`. So I decided not to include these method in the benchmark.

I'll think about this and the other issues you opened.

**Comment by fabiolimace** [comment]
I will do some changes in the [ulid-creator](https://github.com/f4b6a3/ulid-creator) project before releasing a minor version.

After that I'll include both in the benchmark project:
https://github.com/fabiolimace/uuid-creator-benchmark

**Comment by nimo23** [comment]
Ok. Thanks!
