### ISSUE TITLE
Doc bug

### ISSUE THREAD

**Issue by xenoterracide** [f4b6a3/uuid-creator#72]
> UUID uuid = UuidCreator.getTimeOrderedEpoch();

doesn't exist, not sure about more

**Comment by fabiolimace** [comment]
Could you explain?

**Comment by xenoterracide** [comment]
Sorry, I guess I thought it was obvious. I got that code from your readme but that static function doesn't actually exist. I haven't gone through all of readme to see how accurate it is. I suspect it deserves a good run through.

**Comment by fabiolimace** [comment]
Now I get it. Thanks!

The function was added in version 5.0.0. Which version are you using?

By the way, I need to rewrite the readme. This file has too much stuff. Most of the time, people just want to generate a UUID of a certain type. They don't need to know everything in the package at once. I'll try to make this file leaner and with fewer grammar mistakes.

**Comment by xenoterracide** [comment]
What version I'm using is a good question. I'll check Monday as I haven't updated the dynamic version in a bit... Whatever major version it was that I talked you into adding the auto module for Java support

**Comment by xenoterracide** [comment]
ok, I was on version 3, it does exist on version 5, sorry I'm very used to things upgrading with spring and didn't think to check.

**Comment by xenoterracide** [comment]
Side comment, I think most of the time people just want to know which is the best version to use for persisting stuff to a database without indexing problems.
