### ISSUE TITLE
consider the (optional) use of ThreadLocal(Random)

### ISSUE THREAD

**Issue by nimo23** [f4b6a3/uuid-creator#8]
The uuid-creator (and ulid-creator) uses internally `java.util.Random `. This could lead to contention (and latency) if a very high number of threads generate uuid/ulid at the same time. Because java uses a single shared `SecureRandom` (and `Random`) instance to generate the random bits. 

The `java.util.concurrent.ThreadLocalRandom` extends `Random` to eliminate such issues. Maybe you can include this idea within the Generator-Patterns of uuid and ulid (e.g., .withTreadLocal()). 

```
UuidCreator
.getUlidBasedCreator()
.withTreadLocal()
.withFastRandomGenerator()
```

Another alternative is to put the SecureRandom (Random) or any other Random derived classes into a `ThreadLocal` (don't forget to  `remove()` the thread local to avoid memory leaks). 

Another alternative is to use a buffer of precreated uuid/ulids:

```
UuidCreator
.getUlidBasedCreator()
// uses a buffer if available by a previous call or creates one with 1000
// the next caller gets the value from the buffer
.fromBuffer(1000)
.withFastRandomGenerator()
```

But I think the TreadLocal-approach would be good enough.

**Comment by fabiolimace** [comment]
I think it's a very good idea. I'll do it in the next days.

**Comment by fabiolimace** [comment]
I added methods to switch to ThreadLocalRandom in RandomUuidCreator and UlidBasedGuidCreator, if necessary. I think it is good enough, although it is not the best solution due to the risk of memory leak.

I prefer the second option, but I honestly don't know how to use SecureRandom with ThreadLocal without risk of memory leak on the application servers. I included a static ThreadLocal<SecureRandom> in RandomUtil, but I gave up because I didn't know if going could cause GC-related problems.

**Comment by nimo23** [comment]
With second option you mean `ThreadLocal.withInitial` or the buffer-solution?

>how to use SecureRandom with ThreadLocal without risk of memory leak on the application servers

Yes, good point. I find out that `UUID.randomUUID()` on Java 8+ removed the `synchronized` and uses `/dev/urandom`  (-> non-blocking) instead of `/dev/random` (-> blocking). Read more: https://tersesystems.com/blog/2015/12/17/the-right-way-to-use-securerandom/

According to the measurement of https://github.com/apache/openwhisk/issues/2747, _ThreadLocal[SecureRandom]_ is also prefered instead of _ThreadLocalRandom_. But I don't know _if or how_ they solve the potential memory leaks when using _ThreadLocal[SecureRandom]_ (https://github.com/apache/openwhisk/pull/2785/commits/f66c78d117cbb941ca8671732dd59546df804eae). Btw, the objects stored in the ThreadLocal are from the system ClassLoader, not the webapp's ClassLoader..so the potential memory leak can occur on the system class loader..

Maybe the pooling-solution (which acts like a buffer) is a better solution? But then the pooling will always preserves numbers in the memory..I think _ThreadLocal[SecureRandom]_ is a clean solution but I am unsure how to treat potential memory leaks..

**Comment by fabiolimace** [comment]
I separated the reusable code in another repository:

https://github.com/f4b6a3/commons

I decided to use `ThreadLocal[SecureRandom]` in the `RandomUtil` class.

```java
protected static final ThreadLocal<Random> THREAD_LOCAL_RANDOM = ThreadLocal.withInitial(SecureRandom::new)
```
Thanks for you help!

**Comment by nimo23** [comment]
Thanks again!
